### ISSUE TITLE
Parented prefab scene object has wrong position on client

### ISSUE THREAD

**Issue by maxkratt** [FirstGearGames/FishNet#738]
**General**
Unity version: 6000.0.5f1
Fish-Networking version: 4.3.8
Discord link: https://discord.com/channels/424284635074134018/1265656545962627103/1265656545962627103
Credit to anvi1900 on Discord for finding this and making the replicable example

**Description**
When joining as a client, the a parented prefab scene object appears near the world origin instead of its starting location.

**Replication**
1. Import example package
2. Run a server
3. Run a separate client
4. One of the objects is in the wrong position on the client

**Expected behavior**
That the object respects its position.

**Example Package**
[MisplacedObjects.zip](https://github.com/user-attachments/files/16394640/MisplacedObjects.zip)

![image](https://github.com/user-attachments/assets/39e8c91b-9d13-4add-bcd1-dd333f5a44f1)

**Comment by hesham-akmal** [comment]
4.3.7R as well

**Comment by Sod3n** [comment]
As i see, it sets global position, but server sends local position of object to client. Not sure if problem that HasParent of networkobject is false or server should send global position. In my project (didn`t check in example package, leave it for someone else) you can check it like this:
```
private void SetParentAndTransformProperties(CachedNetworkObject cnob)
        {
            if (!_networkManager.IsHostStarted && cnob.NetworkObject != null)
            {
                //Apply runtime parent if needed.
                if (cnob.HasParent)
                {
                    if (_networkManager.ClientManager.Objects.Spawned.TryGetValueIL2CPP(cnob.ParentObjectId.Value, out NetworkObject parentNob))
                    {
                        //If parented to the NOB directly.
                        if (!cnob.ParentComponentIndex.HasValue)
                            cnob.NetworkObject.SetParent(parentNob);
                        //Parented to a NB.
                        else
                            cnob.NetworkObject.SetParent(parentNob.NetworkBehaviours[cnob.ParentComponentIndex.Value]);
                    }
                    else
                    {
                        _networkManager.Log($"Parent NetworkObject Id {cnob.ParentObjectId} could not be found in spawned. NetworkObject {cnob.NetworkObject} will not have it's parent set.");
                    }

                    cnob.NetworkObject.transform.SetLocalPositionRotationAndScale(cnob.Position, cnob.Rotation, cnob.Scale);
                    Debug.LogError($"HasParent {cnob.NetworkObject.gameObject.name} {cnob.Position}");
                }
                else
                {
                    Debug.LogError($"NoParent {cnob.NetworkObject.gameObject.name} {cnob.Position}");
                    cnob.NetworkObject.transform.SetWorldPositionRotationAndScale(cnob.Position, cnob.Rotation, cnob.Scale);
                }
            }
        }
```

Maybe this info will help someone who take this case. I also will try to dig deeper later and let you know if find some new info.

**Comment by IrishMerlin** [comment]
Ah, ran into this issue as well. What was the solution? Either that or how long until the next release with the fix?

**Comment by IrishMerlin** [comment]
Tested in FishNet v4.4.0R Pro, still having the same issue.

**Comment by maxkratt** [comment]
Can confirm this is still happening. Here is a video demonstrating it in 4.4.0 pro:

https://github.com/user-attachments/assets/01038224-744d-4ca4-9a5d-4845bec500a3

**Comment by FirstGearGames** [comment]
There were two parts causing this issue, one was resolved in 4.4.0 which fixed it in my tests. The second part has been identified and resolved as well. Resolved in 4.4.1.

**Comment by Aviit** [comment]
Bug persist in 4.4.1. Bug can be replicated to in the example project in the original post.

**Comment by FirstGearGames** [comment]
Are you moving the nested after server starts? I was able to replicate by
doing that but not by leaving it as is then connecting client.

**Comment by FirstGearGames** [comment]
> Bug persist in 4.4.1. Bug can be replicated in the example project in the original post.

I am fairly sure this is being caused via Unity serialization bug. I was able to replicate it under a few different conditions, all of which were because Unity did not serialize the file properly.

I'm going to try some different ways to go about this where the Unity editor won't break it.

**Comment by IrishMerlin** [comment]
v4.1.1, I can confirm some of the objects are at the correct position, some at near world origin. I'm going to change the position slightly to change serialization value or something.

**Comment by IrishMerlin** [comment]
Okay. Got it. After few hours of tracking down, I found that if I have EmptyNetworkBehaviour on parent game object, the children network objects gets moved to world origin. @Aviit, I do not know if that would be the same case for you, but can check for any EmptyNetworkBehaviour and remove it - see if that solved it for you. @maxkratt maybe you can check this too?

@FirstGearGames, now with knowing this, does this help you know what we can do to solve the issue? Should we not use EmptyNetworkBehaviour at all or ... ?

**Comment by IrishMerlin** [comment]
Got 99% of my scene working, but only issue is the draggable object which needs to have NetworkTransform with synchronize parent and the parent object to have EmptyNetworkBehaviour - that's where I still have an issue with.

**Comment by IrishMerlin** [comment]
Last update: I grabbed MisplacedObjects scene in the above zip file and tried the Empty Network Behaviour but wasn't able to reproduce the issue. I guess unity serialization bug after all.

**Comment by FirstGearGames** [comment]
I did a refactor on the transform placement for spawns and _mostly_ everything is working. At the moment the only thing which seems incorrect is the parent is not being updated for clients in the spawn message or at runtime with a NetworkTransform.

This is probably a rather small issue so I hope to have this ready for testing soon.

**Comment by FirstGearGames** [comment]
All tests passed in latest version! Resolved pending release.

**Comment by FirstGearGames** [comment]
Resolved in 4.4.2
