### ISSUE TITLE
Spawn on wrong scene

### ISSUE THREAD

**Issue by f2069** [FirstGearGames/FishNet#765]
**General**
Unity version: 2021.3.18f1
Fish-Networking version: 4.3.8R Pro, 4.4.6R Pro
Discord link: https://discord.com/channels/424284635074134018/1278964236172918784

**Description**
When a client connects to the Global network scene, some NetworkObjects spawn in the "MovedObjectsHolder" scene, which is incorrect.

**Replication**
1. Open the "SpawnOnLoad.Menu" scene in both windows;
2. Start the Server and Client in one window;
3. Press the "Load Scene" button and wait until the "SpawnOnLoad.Game" scene was loaded;
4. In the second window (clone) start client;
5. When the client connects to the server scene, some NetworkObjects appear in the "MovedObjectsHolder" scene.

**Expected behavior**
When the client connects to the server scene, all network objects should spawn in the "SpawnOnLoad.Game" scene.
The "MovedObjectsHolder" scene should remain empty, as it does on the server.

**Screenshots**
<img width="2048" alt="SpawnOnLoad bug" src="https://github.com/user-attachments/assets/6ce3b8c7-f3e6-413b-b7d5-7de751fb094e">

**Video**
https://youtu.be/-PbLIhg9Ny8

**Package**
[SpawnOnLoad.v4.4.6.unitypackage.zip](https://github.com/user-attachments/files/17128006/SpawnOnLoad.v4.4.6.unitypackage.zip)

I think this happens because the client has not yet loaded the correct scene, but sets "MovedObjectsHolder" as the active scene, receives spawn messages, and places objects there. Then, the correct scene is finally loaded, and other objects are placed correctly.

It's possible that the "MovedObjectsHolder" scene is being created without a real reason, or objects are spawning in the wrong scene.
I haven't found a solution to properly chain objects and scenes together.

This issue is critical because important objects are spawning in the wrong scene in the actual game, causing references to be lost and breaking gameplay for the client.

In version 4.4.4R Pro, the same behavior is observed, but we are currently unable to upgrade our project due to numerous errors encountered after migration.

**Comment by stilnat** [comment]
I'm experiencing a very similar issue with fishnet 4.4.3 and Unity 2021.3.43f1 : 
When loading a scene with the option ReplaceOption.All, The MovedObjectsHolder scene become the active scene (I did not move anything at all).

I'm using this simple code to load the scene

```
SceneLoadData sld = new SceneLoadData("Lobby");
NetworkConnection[] conns = {conn};
sld.ReplaceScenes = ReplaceOption.All;
InstanceFinder.SceneManager.LoadConnectionScenes(conns, sld);

```
The clients correctly load the scene, but they don't set it as the active scene. (I'll make a MRE if necessary, but I believe the above one should be enough)

**Comment by FirstGearGames** [comment]
When replacing all the Lobby scene in your case is intended to be the active scene. This appears to be a bug.

**Comment by mrsnaveris** [comment]
I'm having the same issue, reverted back to 4.4.3 and no issues.

**Comment by FirstGearGames** [comment]
Unusual given the active scene code has not been touched between those two versions. The spawning code was refactored, but that never touched what scene objects spawn in. 

I'll try the code below, thank you!
```cs
SceneLoadData sld = new SceneLoadData("Lobby");
NetworkConnection[] conns = {conn};
sld.ReplaceScenes = ReplaceOption.All;
InstanceFinder.SceneManager.LoadConnectionScenes(conns, sld);
```

**Comment by FirstGearGames** [comment]
Find this method inside our **SceneManager.cs** file.

```cs
void SetActiveScene_Local()```

Replace with this and the issue should be fixed.
```cs
                void SetActiveScene_Local()
                {
                    bool byUser;
                    Scene preferredActiveScene = GetUserPreferredActiveScene(sceneLoadData.PreferredActiveScene, asServer, out byUser);
                    //If preferred still is not set then try to figure it out.
                    if (!preferredActiveScene.IsValid())
                    {
                        bool setToFirstLookup = false;
                        //If any scenes are being replaced see if active needs to be updated.
                        if (sceneLoadData.ReplaceScenes != ReplaceOption.None)
                        {
                            //If load is for a connection and server isnt started.
                            setToFirstLookup |= (data.ScopeType == SceneScopeType.Connections && !NetworkManager.IsServerStarted);
                            /* If current active is the movedObjectsHolder, such as moved objects.
                             * This can happen when replacing a scene that was active and the next in line is
                             * set by unity as one of the temp scenes. */
                            Scene activeScene = UnitySceneManager.GetActiveScene();
                            setToFirstLookup |= (activeScene == GetMovedObjectsScene());
                        }
                        
                        if (setToFirstLookup)
                            preferredActiveScene = sceneLoadData.GetFirstLookupScene();
                    }

                    SetActiveScene(preferredActiveScene, byUser);
                }
```

**Comment by f2069** [comment]
After update to 4.4.6R Pro behaviour doesn't changed.
I updated video link and the package in description.

**Comment by maxkratt** [comment]
I can conform that this is still happening as mentioned above. Tested with one server and a solo client connected then the server pressed the load scene button and the client had several objects show up in the MovedObjectsHolder scene. It also happened if the server started and loaded the scene before the client connected.

**Comment by FirstGearGames** [comment]
Using the same package in the first comment?

**Comment by FirstGearGames** [comment]
This does not appear to be a bug.

I noticed you are not utilizing the observer manager/scene condition. Without that condition objects can spawn even if the client doesn't have visibility of the scene they reside. This means, if the client does not have the scene fully loaded or not loaded at all, they can still receive the spawn message and the objects will instantiate in whichever scene is active.

Removing your 'ignore manager' condition, and adding scene condition as default on ObserverManager solved the problem.
